version: '3.7'

services:
  api-gateway:
    image: imagynetech/eatlater-api-gateway:latest
    env_file:
      - ./config/api-gateway/.env
    depends_on:
      - rabbitmq
    ports:
      - '3000:3000'
    networks:
      - app-tier
  vendor-gateway:
    image: imagynetech/eatlater-vendor-gateway:latest
    env_file:
      - ./config/vendor-gateway/.env
    depends_on:
      - rabbitmq
    ports:
      - '3001:3001'
    networks:
      - app-tier
  users-service:
    image: imagynetech/eatlater-users-service:latest
    env_file:
      - ./config/users-service/.env
    depends_on:
      - api-gateway
      - users-db
      - rabbitmq
    networks:
      - app-tier
  notification-service:
    image: imagynetech/eatlater-notification-service:latest
    env_file:
      - ./config/notification-service/.env
    depends_on:
      - api-gateway
      - rabbitmq
    networks:
      - app-tier
  vendors-service:
    image: imagynetech/eatlater-vendors-service:latest
    env_file:
      - ./config/vendors-service/.env
    depends_on:
      - vendor-gateway
      - vendors-db
      - rabbitmq
    networks:
      - app-tier
  listings-service:
    image: imagynetech/eatlater-listings-service:latest
    env_file:
      - ./config/listings-service/.env
    depends_on:
      - listings-db
      - vendor-gateway
      - rabbitmq
    networks:
      - app-tier
  orders-service:
    image: imagynetech/eatlater-orders-service:latest
    env_file:
      - ./config/orders-service/.env
    depends_on:
      - orders-db
      - api-gateway
      - rabbitmq
    networks:
      - app-tier
  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
    volumes:
      - rabbitmq_data_playground:/var/lib/rabbitmq
    networks:
      - app-tier
  users-db:
    image: bitnami/postgresql:14
    ports:
      - '5432'
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=root@123
      - POSTGRESQL_DATABASE=users
    volumes:
      - pg_data:/var/lib/postgresql
    networks:
      - app-tier
  vendors-db:
    image: bitnami/postgresql:14
    ports:
      - '5432'
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=root@123
      - POSTGRESQL_DATABASE=vendors
    volumes:
      - pg_data:/var/lib/postgresql
    networks:
      - app-tier
  listings-db:
    image: bitnami/postgresql:14
    ports:
      - '5432'
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=root@123
      - POSTGRESQL_DATABASE=listings
    volumes:
      - pg_data:/var/lib/postgresql
    networks:
      - app-tier
  orders-db:
    image: bitnami/postgresql:14
    ports:
      - '5432'
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=root@123
      - POSTGRESQL_DATABASE=orders
    volumes:
      - pg_data:/var/lib/postgresql
    networks:
      - app-tier
volumes:
  rabbitmq_data_playground:
    driver: local
  pg_data:
    driver: local
networks:
  app-tier:
    driver: bridge
