export enum OrderScreenName {
    ORDERS = 'ORDERS',
    UNDELIVERED_SINGLE_ORDER = 'UNDELIVERED_SINGLE_ORDER',
    DELIVERED_SINGLE_ORDER = 'DELIVERED_SINGLE_ORDER',
    TRACK_ORDER = 'TRACK_ORDER',
    ADD_REVIEW = 'ADD_REVIEW'
}
